//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistenciaDiaAsignatura
    {
        public string Persona { get; set; }
        public string CursoCod { get; set; }
        public string CursoNombre { get; set; }
        public string CodAsignatura { get; set; }
        public int ConvocatoriaNum { get; set; }
        public int EvaluacionNum { get; set; }
        public int SemanaNombre { get; set; }
        public int DiaNombre { get; set; }
        public Nullable<int> FaltasAsistencia { get; set; }
        public Nullable<int> FaltasAsistenciaJustificadas { get; set; }
    
        public virtual AsistenciaSemanaAsignatura AsistenciaSemanaAsignatura { get; set; }
    }
}
