//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificado
    {
        public string Alumno { get; set; }
        public string CursoCod { get; set; }
        public string CursoNombre { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaDisponible { get; set; }
        public Nullable<System.DateTime> FechaRecogido { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public Nullable<bool> EnTramite { get; set; }
        public Nullable<double> Importe { get; set; }
    
        public virtual Alumno Alumno1 { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual CertificadoMatricula CertificadoMatricula { get; set; }
        public virtual CertificadoNotas CertificadoNotas { get; set; }
        public virtual CertificadoTitulo CertificadoTitulo { get; set; }
        public virtual Titulo Titulo { get; set; }
    }
}
