//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciclo
    {
        public string Cod { get; set; }
        public string Nombre { get; set; }
        public bool Basica { get; set; }
        public int HorasPractica { get; set; }
        public string Rama { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Superior Superior { get; set; }
    }
}
