//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convocatoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Convocatoria()
        {
            this.Evaluacion = new HashSet<Evaluacion>();
        }
    
        public string Alumno { get; set; }
        public string CursoCod { get; set; }
        public string CursoNombre { get; set; }
        public string CodAsignatura { get; set; }
        public int Num { get; set; }
        public Nullable<bool> Renunciada { get; set; }
    
        public virtual Alumno Alumno1 { get; set; }
        public virtual Asignatura Asignatura { get; set; }
        public virtual Curso Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
    }
}
