//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbastosEntities : DbContext
    {
        public AbastosEntities()
            : base("name=AbastosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrativo> Administrativo { get; set; }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Asignatura> Asignatura { get; set; }
        public virtual DbSet<AsistenciaDiaAsignatura> AsistenciaDiaAsignatura { get; set; }
        public virtual DbSet<AsistenciaSemanaAsignatura> AsistenciaSemanaAsignatura { get; set; }
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<Bachiller> Bachiller { get; set; }
        public virtual DbSet<Baja> Baja { get; set; }
        public virtual DbSet<Certificado> Certificado { get; set; }
        public virtual DbSet<CertificadoMatricula> CertificadoMatricula { get; set; }
        public virtual DbSet<CertificadoNotas> CertificadoNotas { get; set; }
        public virtual DbSet<CertificadoTitulo> CertificadoTitulo { get; set; }
        public virtual DbSet<Ciclo> Ciclo { get; set; }
        public virtual DbSet<Convocatoria> Convocatoria { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Eso> Eso { get; set; }
        public virtual DbSet<Especial> Especial { get; set; }
        public virtual DbSet<Evaluacion> Evaluacion { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Impartimiento> Impartimiento { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimiento { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        public virtual DbSet<Ordenador> Ordenador { get; set; }
        public virtual DbSet<PermisosUsuario> PermisosUsuario { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<ProfesorSustituto> ProfesorSustituto { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Reclamacion> Reclamacion { get; set; }
        public virtual DbSet<Superior> Superior { get; set; }
        public virtual DbSet<Telefono> Telefono { get; set; }
        public virtual DbSet<Titulo> Titulo { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
