//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluacion()
        {
            this.AsistenciaSemanaAsignatura = new HashSet<AsistenciaSemanaAsignatura>();
        }
    
        public string Alumno { get; set; }
        public string CursoCod { get; set; }
        public string CursoNombre { get; set; }
        public string CodAsignatura { get; set; }
        public int ConvocatoriaNum { get; set; }
        public int EvaluacionNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsistenciaSemanaAsignatura> AsistenciaSemanaAsignatura { get; set; }
        public virtual Convocatoria Convocatoria { get; set; }
        public virtual Nota Nota { get; set; }
    }
}
