//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impartimiento
    {
        public string Profesor { get; set; }
        public string CursoCod { get; set; }
        public string CursoNombre { get; set; }
        public string CodAsignatura { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public int Dia { get; set; }
        public int Anyo { get; set; }
        public int HoraFinal { get; set; }
        public string AulaNum { get; set; }
        public string AulaPiso { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Profesor Profesor1 { get; set; }
    }
}
