//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public string Alumno { get; set; }
        public string CursoCod { get; set; }
        public string CursoNombre { get; set; }
        public string CodAsignatura { get; set; }
        public int ConvocatoriaNum { get; set; }
        public int EvaluacionNum { get; set; }
        public double Valoracion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Evaluacion Evaluacion { get; set; }
    }
}
