//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenador
    {
        public string Num { get; set; }
        public string Piso { get; set; }
        public string Estado { get; set; }
        public string CodOrdenadorAula { get; set; }
        public string Ip { get; set; }
        public string SistemaOperativo { get; set; }
    
        public virtual Aula Aula { get; set; }
    }
}
