//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public string Alumno { get; set; }
        public string SuperiorCod { get; set; }
        public string SuperiorNombre { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Memoria { get; set; }
        public string Contenido { get; set; }
        public string Tutor { get; set; }
        public Nullable<double> Nota { get; set; }
    
        public virtual Alumno Alumno1 { get; set; }
        public virtual Superior Superior { get; set; }
    }
}
