//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamacion
    {
        public string Alumno { get; set; }
        public int NumParte { get; set; }
        public string Asunto { get; set; }
        public string Contenido { get; set; }
        public string DirigidoA { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public string Respuesta { get; set; }
        public string Revisor { get; set; }
        public Nullable<bool> EnTramite { get; set; }
    
        public virtual Alumno Alumno1 { get; set; }
    }
}
