//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public string Persona { get; set; }
        public string Telefono1 { get; set; }
        public string Comentario { get; set; }
    
        public virtual Persona Persona1 { get; set; }
    }
}
