//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.Baja = new HashSet<Baja>();
        }
    
        public string Persona { get; set; }
        public double Sueldo { get; set; }
        public System.DateTime FechaIncorporacion { get; set; }
    
        public virtual Administrativo Administrativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baja> Baja { get; set; }
        public virtual Especial Especial { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
