//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Persona { get; set; }
        public string Username { get; set; }
        public string Contrasenya { get; set; }
        public string Nombre { get; set; }
        public bool PermisoAdministrativo { get; set; }
        public bool PermisoAdmin { get; set; }
        public bool PermisProfesor { get; set; }
        public bool PermisoAlumno { get; set; }
    
        public virtual PermisosUsuario PermisosUsuario { get; set; }
        public virtual Persona Persona1 { get; set; }
    }
}
